### ISSUE TITLE
Error while logging in

### ISSUE THREAD

**Issue by dgopstein** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#103]
I tried to log in to the system with the same credentials I used last week and after clicking login I was greeted with a stack trace.

![image](https://user-images.githubusercontent.com/3387679/68346293-c01c7500-00c1-11ea-9d1f-701ff98e18c8.png)

![image](https://user-images.githubusercontent.com/3387679/68346247-a3803d00-00c1-11ea-957f-cddf09072d77.png)

**Comment by ppietraszko** [comment]
It is something I handled at the form level and locally it was fixed. It must have not been pushed through to master. We will create a bug to make sure it is handled.
