### ISSUE TITLE
Valid Registration Form Inputs

### ISSUE THREAD

**Issue by ahanif19** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#154]
## Expected Behavior
In general, would think names should probably only be allowed to include letters and maybe dashes?

## Current Behavior
I provided the first name '123456' and my registration form was accepted

## Ideas for Improvement
Maybe consider adding methods to clean the form fields?

## Steps to Reproduce
1. Begin Here
2. Create Account
3. Type in '123456' as first name
4. Complete the rest of the form and click Register

## Context (Environment)
This does not hamper the user experience/ability to perform tasks in any material way but think it would still be good to check/validate this

![image](https://user-images.githubusercontent.com/54873399/69659540-6669f380-104c-11ea-9494-f06dbf0e433b.png)

**Comment by snehalkenjale** [comment]
As discussed with the team, we won't be adding the validation on first, last names.
