### ISSUE TITLE
Can't apply to a school that doesn't have a program

### ISSUE THREAD

**Issue by ahanif19** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#158]
## Expected Behavior
Student should be able to apply to a school that doesn't offer multiple programs without providing any input in the "Program" field.

## Current Behavior
I am trying to apply to a school that doesn't offer multiple programs (Stuyvesant High School) but the form won't allow me to submit without providing a program

## Ideas for Improvement
Maybe don't make the program a required field or try to have it only be required if programs exit

## Steps to Reproduce
1. Log in a student
2. Click apply
3. Fill out all of the form fields
4. Select Stuyvesant High School
5. Trying to add a program and submit

![image](https://user-images.githubusercontent.com/54873399/69660814-1e989b80-104f-11ea-9c01-f437d89ae7ab.png)

**Comment by de846** [comment]
I have the same issue

**Comment by snehalkenjale** [comment]
This issue has been fixed, hence closing
