### ISSUE TITLE
Password reset button does not work

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#164]
Clicking on the Change Password button when logged in as a student does nothing.

## Expected Behavior

The page should redirect to or present some forms or so for changing password.

## Current Behavior

The button does nothing.

## Ideas for Improvement

Either allow the user to reset password, or temporarily remove this button before it works.
Better to ship software that works.

## Steps to Reproduce
1. Log in as a student.
2. Click on the username at the top right corner of the page, to reveal the action sheet.
3. Click on Change Password. And nothing happens, apart from the sheet disappears.

## Context (Environment)
Safari Version 13.0.3 (15608.3.10.1.4).

**Comment by snehalkenjale** [comment]
It has been stated in the ReadMe that this functionality is not currently implemented.
