### ISSUE TITLE
Admin and Student login portal looks the same

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#165]
Two user login portals look the same.

## Expected Behavior

There should be more distinguishing features on these two pages to guide user.

## Current Behavior

Two pages have the same appearance, with the only difference being the trivia on the right.

## Ideas for Improvement

Use visually outstanding elements to highlight the portal user type.

## Steps to Reproduce
1. In one browser tab, go to admin login portal, [https://oneapply.herokuapp.com/login/ut_admin_staff/login_user](https://oneapply.herokuapp.com/login/ut_admin_staff/login_user)
2. In another tab, go to student login portal, [https://oneapply.herokuapp.com/login/ut_student/login_user](https://oneapply.herokuapp.com/login/ut_student/login_user)
3. Switch between the portals, and quickly it will be increasingly hard to tell which is which.

## Context (Environment)
Safari Version 13.0.3 (15608.3.10.1.4)

**Comment by snehalkenjale** [comment]
the user will either be a student or an admin in almost all cases so it will not matter if the dashboards will be similar
