### ISSUE TITLE
Student Birthdates Too Tightly Restricted

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#166]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
A student applying for high school should be able to input their date of birth.

## Current Behavior
Currently dates of birth are restricted to be between 11 and 15 years old. This neglects students that start high school late (or extremely early). Its not uncommon to start high school after 16, or to transfer high schools after turning 16, but these users are currently locked out from the app.

## Ideas for Improvement
Remove DOB age restriction.

## Steps to Reproduce

1. Input a DOB less that 11 or greater than 16

**Comment by snehalkenjale** [comment]
Duplicate issue hence closing.
