### ISSUE TITLE
Can't Submit Application due to Phone Number

### ISSUE THREAD

**Issue by MichaelLally** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#167]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
User should be able to enter a phone number for themselves and their guardian on the High School Application Form page.

## Current Behavior
Can't submit because no phone number will be accepted. Even if you copy the exact number from the error message "Enter a valid phone number (e.g. +12125552368).", +12125552368 or 12125552368 do not work as valid number.

## Steps to Reproduce

1. Type in any real phone number and see how it behaves.

**Comment by snehalkenjale** [comment]
Fixed hence closing
