### ISSUE TITLE
"Password change" isn't working

### ISSUE THREAD

**Issue by Ayushi-0903** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#169]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I click on "Password change" it doesn't direct me to any page. "Password Change " isn't working

## Expected Behavior
It should direct to the page of changing password or send me link to change password. 

## Current Behavior
"Change password" option is available but functionality isn't working.

## Ideas for Improvement
Should implement the fuctionality.

## Context (Environment)
If I forget my password or would like to change my password, then ?

**Comment by snehalkenjale** [comment]
It has been stated in the ReadMe that this functionality has not been implemented yet.
