### ISSUE TITLE
Age Restriction on High School App

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#172]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The High school application form restricts age to 11-15 years. This seems odd to me since it says "High School" application but 11-15 is definitely not high school age.

## Expected Behavior
If there has to be an age range restriction, it seems more likely that it should be 13-17 than 11-15.

## Current Behavior
Restricts to 11-15

## Ideas for Improvement
This age range seems more applicable to Middle school. Maybe I just don't understand the NY school system but the form name should reflect the age group allowed to enter.

## Steps to Reproduce

1. Enter a date greater than 15 years ago in High School Application form
2. attempt to submit.

**Comment by snehalkenjale** [comment]
As discussed with the team, we will be keeping the age restriction to 11-15 years.
