### ISSUE TITLE
Floating point weirdness in GPA recommendation

### ISSUE THREAD

**Issue by de846** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#175]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
I shouldn't be able to type in weird GPAs and then get recommendations that I cannot follow.

## Current Behavior
It suggests to use values which are also not valid (see image below).
## Ideas for Improvement
Only allow for a regex of `\d\.[\d]2` on the client.
## Steps to Reproduce
1. Use a long floating point value for GPA
2. Attempt to save as draft

![image](https://user-images.githubusercontent.com/16791467/69688205-60e3cc00-1093-11ea-81a3-059388d3c8d0.png)

**Comment by snehalkenjale** [comment]
We are not able to reproduce this issue on our side.

![bug](https://user-images.githubusercontent.com/38788082/69742364-a8596f00-110a-11ea-91f9-e8a8688256bd.PNG)
