### ISSUE TITLE
Have to provide personal details when applying to every school

### ISSUE THREAD

**Issue by shaurya133** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#176]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Whenever I apply to a new High schools, I have to re-enter my details such as DOB, Address, Parent's name which is time consuming.

## Expected Behavior

Ideally, the user should be able to create a profile where all these details are saved so that the user can just directly apply to the high school and provide any high school specific details if needed.

## Current Behavior

Right now, I have to enter DOB, Address, Phone number, Parent's name, Parent's phone number every time I apply to a different high school.

## Ideas for Improvement

I would suggest creating a user profile where all the personal details of users are collected so they don't have to enter it every time.  

## Steps to Reproduce

1. Sign up and Log in
2. Click on Apply
3. High School Application form shows up

Some suggestions for the UI:
1) The compulsory fields should have (*) next to them.
2) It would be better to see good quality pictures included on the homepage.

Other than that the UI looks pretty good and the application is really close to MLP. Good job.

**Comment by snehalkenjale** [comment]
We have fixed this, hence closing
