### ISSUE TITLE
Review NYC open data set integration files

### ISSUE THREAD

**Issue by abe-shek** [gcivil-nyu-org/fall2019-cs-gy-6063-team-three#68]
Review 2 files - 
- File 1 -> High School Info Field List
https://docs.google.com/spreadsheets/d/1bLedpyEfeK0LcXq5cY92FwYuoGqvlRxsxRZ9NJW_mms/edit#gid=0
- File 2 -> NYC Open Dataset - Integration notes
 https://docs.google.com/document/d/18FZNSOojv-pGjJSGecbLsPYc_AaoUqfIQVSGnYuHRTQ/edit

Files can also be found in the drive folder under Sprint 7. 

Read the comments included in File 1 and read the proposed options for integration and mark your comments (can be done over slack).

**Comment by ppietraszko** [comment]
Added my input on the form directly

**Comment by snehalkenjale** [comment]
reviewed

**Comment by varshasivakumar** [comment]
I added my input on the form.

**Comment by jinchuhan2009** [comment]
reviewed.
